version: "3.8"
services:
  react-app:
    environment:
      - AUTH = false
    build:
      context: .
    ports:
      - "8081:8080"
    networks:
      - Blognetwork
networks:
  Blognetwork:
    driver: bridge
